const tours={
"buggy-litoral-leste":{name:"Buggy — Litoral Leste",type:"Buggy",lead:"Conheça alguns dos principais cartões-postais do lado leste de Jericoacoara.",description:"Descubra Jericoacoara em um dos passeios mais tradicionais da vila, com uma experiência dedicada às paisagens do Litoral Leste.",image:"buggy.jpg",related:["buggy-litoral-oeste","buggy-barrinha","quadriciclo-litoral-leste"]},
"buggy-litoral-oeste":{name:"Buggy — Litoral Oeste",type:"Buggy",lead:"Explore as paisagens, dunas e atrações do lado oeste de Jericoacoara.",description:"Viva o clássico passeio de buggy em uma experiência voltada aos cenários naturais do Litoral Oeste.",image:"buggy.jpg",related:["buggy-litoral-leste","buggy-barrinha","4x4-litoral-oeste"]},
"buggy-barrinha":{name:"Buggy — Barrinha",type:"Buggy",lead:"Viva uma experiência especial pela região da Barrinha e seus cenários naturais.",description:"Conheça a região da Barrinha em um dos passeios mais tradicionais de Jericoacoara.",image:"buggy.jpg",related:["buggy-litoral-leste","buggy-litoral-oeste","utv-barrinha"]},
"quadriciclo-litoral-leste":{name:"Quadriciclo — Litoral Leste",type:"Quadriciclo",lead:"Explore as principais atrações do lado leste de Jericoacoara de quadriciclo.",description:"Uma experiência com aventura e liberdade dedicada às paisagens do Litoral Leste.",image:"quadriciclo.jpg",related:["quadriciclo-litoral-oeste","quadriciclo-barrinha","buggy-litoral-leste"]},
"quadriciclo-litoral-oeste":{name:"Quadriciclo — Litoral Oeste",type:"Quadriciclo",lead:"Conheça dunas, praias e paisagens incríveis do lado oeste de Jericoacoara.",description:"Explore o Litoral Oeste de quadriciclo, com a liberdade de viver uma experiência mais aventureira.",image:"quadriciclo.jpg",related:["quadriciclo-litoral-leste","quadriciclo-barrinha","utv-litoral-oeste"]},
"quadriciclo-barrinha":{name:"Quadriciclo — Barrinha",type:"Quadriciclo",lead:"Viva uma experiência especial pela região da Barrinha de quadriciclo.",description:"Descubra as paisagens da região da Barrinha com mais aventura e liberdade.",image:"quadriciclo.jpg",related:["quadriciclo-litoral-leste","quadriciclo-litoral-oeste","utv-barrinha"]},
"utv-litoral-leste":{name:"UTV — Litoral Leste",type:"UTV",lead:"Explore praias, lagoas e atrações do litoral leste em uma experiência de UTV.",description:"Viva Jericoacoara com potência, conforto e aventura em uma experiência dedicada ao Litoral Leste.",image:"utv.jpg",related:["utv-litoral-oeste","utv-barrinha","utv-privativo"]},
"utv-litoral-oeste":{name:"UTV — Litoral Oeste",type:"UTV",lead:"Descubra dunas, praias e paisagens incríveis do litoral oeste de Jericoacoara.",description:"Uma experiência de UTV que combina potência e conforto nos cenários do Litoral Oeste.",image:"utv.jpg",related:["utv-litoral-leste","utv-barrinha","utv-sunset"]},
"utv-barrinha":{name:"UTV — Barrinha",type:"UTV",lead:"Explore a região da Barrinha de UTV entre praias, dunas e paisagens inesquecíveis.",description:"Viva a região da Barrinha com potência, conforto e aventura em uma experiência de UTV.",image:"utv.jpg",related:["utv-litoral-leste","utv-litoral-oeste","utv-sunset"]},
"utv-sunset":{name:"UTV Sunset",type:"UTV",lead:"Uma experiência especial nas Dunas de Barrinha, no final da tarde, para contemplar o pôr do sol.",description:"Criada para viver um dos momentos mais marcantes de Jericoacoara com exclusividade, emoção e conforto. O roteiro é planejado para aproveitar cada etapa da experiência.",image:"utv.jpg",duration:"Aproximadamente 2 horas",moment:"Final da tarde",related:["utv-barrinha","utv-privativo","paradise-utv-signature"]},
"utv-privativo":{name:"UTV Privativo",type:"UTV",lead:"Uma experiência exclusiva para quem busca mais privacidade, conforto e liberdade.",description:"Conheça Jericoacoara em uma experiência de UTV com proposta privativa.",image:"utv.jpg",mode:"Privativo",related:["utv-sunset","paradise-utv-signature","utv-litoral-leste"]},
"paradise-utv-signature":{name:"Paradise UTV Signature",type:"UTV",lead:"Nossa experiência premium de UTV, criada para viver Jericoacoara de uma forma inesquecível.",description:"Uma proposta premium para quem procura cenário, conforto e valor agregado em Jericoacoara.",image:"utv.jpg",related:["utv-privativo","utv-sunset","utv-barrinha"]},
"4x4-litoral-leste":{name:"4x4 — Litoral Leste",type:"Veículo 4x4",lead:"Conheça as principais atrações do lado leste de Jericoacoara em veículo 4x4.",description:"Descubra Jericoacoara com conforto, segurança e praticidade em uma experiência dedicada ao Litoral Leste.",image:"4x4.jpg",related:["4x4-litoral-oeste","4x4-barrinha","buggy-litoral-leste"]},
"4x4-litoral-oeste":{name:"4x4 — Litoral Oeste",type:"Veículo 4x4",lead:"Explore dunas, praias e paisagens incríveis do lado oeste de Jericoacoara em 4x4.",description:"Conheça o Litoral Oeste com conforto, segurança e praticidade.",image:"4x4.jpg",related:["4x4-litoral-leste","4x4-barrinha","buggy-litoral-oeste"]},
"4x4-barrinha":{name:"4x4 — Barrinha",type:"Veículo 4x4",lead:"Viva uma experiência especial pela região da Barrinha com conforto em veículo 4x4.",description:"Conheça a região da Barrinha com conforto, segurança e praticidade.",image:"4x4.jpg",related:["4x4-litoral-leste","4x4-litoral-oeste","utv-barrinha"]}
};
const key=document.body.dataset.tour;const tour=tours[key];
if(tour){
 document.documentElement.style.setProperty("--hero-image",`url('../${tour.image}')`);
 document.querySelectorAll("[data-tour-name]").forEach(el=>el.textContent=tour.name);
 document.querySelector("[data-tour-lead]").textContent=tour.lead;
 document.querySelector("[data-tour-description]").textContent=tour.description;
 const facts=document.querySelector("[data-facts]");
 const items=[["Tipo de veículo",tour.type],["Duração aproximada",tour.duration],["Horário",tour.moment],["Modalidade",tour.mode]].filter(([,v])=>v);
 facts.innerHTML=items.map(([label,value])=>`<div class="fact"><strong>${label}</strong><span>${value}</span></div>`).join("");
 const message=encodeURIComponent(`Olá! Conheci o passeio ${tour.name} pelo site Jericoacoara Paradise e gostaria de consultar disponibilidade, valores e condições de reserva.`);
 document.querySelectorAll("[data-whatsapp]").forEach(link=>link.href=`https://wa.me/5562984182969?text=${message}`);
 document.querySelector("[data-related]").innerHTML=tour.related.map(id=>{const item=tours[id];return `<a class="recommendation" href="${id}.html"><span>${item.type}</span><h3>${item.name}</h3><p>${item.lead}</p><b>Ver passeio →</b></a>`}).join("");
}
